#pragma once

#include "asset/asset.h"

#define ASSET_TABLE_TOTAL ASSET_ID_TOTAL

static rl_asset asset_table[ASSET_TABLE_TOTAL] = {
    [ASSET_ID_FONT_EVIL_EMPIRE] = (rl_asset){
        .id = ASSET_ID_FONT_EVIL_EMPIRE,
        .type = ASSET_FONT,
        .source_path = "fonts/evil_empire.otf",
        .source_version = 1,
        .source_hash = 0,
        .filename = "evil_empire.otf",
        .handle = nullptr,
    },
    [ASSET_ID_FONT_JETBRAINS_MONO_REGULAR] = (rl_asset){
        .id = ASSET_ID_FONT_JETBRAINS_MONO_REGULAR,
        .type = ASSET_FONT,
        .source_path = "fonts/JetBrainsMono-Regular.ttf",
        .source_version = 1,
        .source_hash = 0,
        .filename = "JetBrainsMono-Regular.ttf",
        .handle = nullptr,
    },
    [ASSET_ID_SHADER_DEFAULT_VERT] = (rl_asset){
        .id = ASSET_ID_SHADER_DEFAULT_VERT,
        .type = ASSET_SHADER,
        .source_path = "shaders/default.vert",
        .source_version = 1,
        .source_hash = 0,
        .filename = "default.vert",
        .handle = nullptr,
    },
    [ASSET_ID_SHADER_TEXT_VERT] = (rl_asset){
        .id = ASSET_ID_SHADER_TEXT_VERT,
        .type = ASSET_SHADER,
        .source_path = "shaders/text.vert",
        .source_version = 1,
        .source_hash = 0,
        .filename = "text.vert",
        .handle = nullptr,
    },
    [ASSET_ID_SHADER_DEFAULT_FRAG] = (rl_asset){
        .id = ASSET_ID_SHADER_DEFAULT_FRAG,
        .type = ASSET_SHADER,
        .source_path = "shaders/default.frag",
        .source_version = 1,
        .source_hash = 0,
        .filename = "default.frag",
        .handle = nullptr,
    },
    [ASSET_ID_SHADER_TEXT_FRAG] = (rl_asset){
        .id = ASSET_ID_SHADER_TEXT_FRAG,
        .type = ASSET_SHADER,
        .source_path = "shaders/text.frag",
        .source_version = 1,
        .source_hash = 0,
        .filename = "text.frag",
        .handle = nullptr,
    },
    [ASSET_ID_SHADER_LIGHT_FRAG] = (rl_asset){
        .id = ASSET_ID_SHADER_LIGHT_FRAG,
        .type = ASSET_SHADER,
        .source_path = "shaders/light.frag",
        .source_version = 1,
        .source_hash = 0,
        .filename = "light.frag",
        .handle = nullptr,
    },
    [ASSET_ID_SHADER_VULKAN_TRIANGLE_FRAG] = (rl_asset){
        .id = ASSET_ID_SHADER_VULKAN_TRIANGLE_FRAG,
        .type = ASSET_SHADER,
        .source_path = "shaders/vulkan_triangle.frag",
        .source_version = 1,
        .source_hash = 0,
        .filename = "vulkan_triangle.frag",
        .handle = nullptr,
    },
    [ASSET_ID_SHADER_VULKAN_TRIANGLE_VERT] = (rl_asset){
        .id = ASSET_ID_SHADER_VULKAN_TRIANGLE_VERT,
        .type = ASSET_SHADER,
        .source_path = "shaders/vulkan_triangle.vert",
        .source_version = 1,
        .source_hash = 0,
        .filename = "vulkan_triangle.vert",
        .handle = nullptr,
    },
    [ASSET_ID_SHADER_VULKAN_TEXT_VERT] = (rl_asset){
        .id = ASSET_ID_SHADER_VULKAN_TEXT_VERT,
        .type = ASSET_SHADER,
        .source_path = "shaders/vulkan_text.vert",
        .source_version = 1,
        .source_hash = 0,
        .filename = "vulkan_text.vert",
        .handle = nullptr,
    },
    [ASSET_ID_SHADER_VULKAN_TEXT_FRAG] = (rl_asset){
        .id = ASSET_ID_SHADER_VULKAN_TEXT_FRAG,
        .type = ASSET_SHADER,
        .source_path = "shaders/vulkan_text.frag",
        .source_version = 1,
        .source_hash = 0,
        .filename = "vulkan_text.frag",
        .handle = nullptr,
    },
    [ASSET_ID_SHADER_GUI_VERT] = (rl_asset){
        .id = ASSET_ID_SHADER_GUI_VERT,
        .type = ASSET_SHADER,
        .source_path = "shaders/gui.vert",
        .source_version = 1,
        .source_hash = 0,
        .filename = "gui.vert",
        .handle = nullptr,
    },
    [ASSET_ID_SHADER_GUI_FRAG] = (rl_asset){
        .id = ASSET_ID_SHADER_GUI_FRAG,
        .type = ASSET_SHADER,
        .source_path = "shaders/gui.frag",
        .source_version = 1,
        .source_hash = 0,
        .filename = "gui.frag",
        .handle = nullptr,
    },
    [ASSET_ID_TEXTURE_WOOD_CONTAINER] = (rl_asset){
        .id = ASSET_ID_TEXTURE_WOOD_CONTAINER,
        .type = ASSET_TEXTURE,
        .source_path = "textures/wood_container.jpg",
        .source_version = 1,
        .source_hash = 0,
        .filename = "wood_container.jpg",
        .handle = nullptr,
    },
    [ASSET_ID_TEXTURE_WOOD_CONTAINER2] = (rl_asset){
        .id = ASSET_ID_TEXTURE_WOOD_CONTAINER2,
        .type = ASSET_TEXTURE,
        .source_path = "textures/wood_container2.jpg",
        .source_version = 1,
        .source_hash = 0,
        .filename = "wood_container2.jpg",
        .handle = nullptr,
    },
    [ASSET_ID_TEXTURE_FACE] = (rl_asset){
        .id = ASSET_ID_TEXTURE_FACE,
        .type = ASSET_TEXTURE,
        .source_path = "textures/face.jpg",
        .source_version = 1,
        .source_hash = 0,
        .filename = "face.jpg",
        .handle = nullptr,
    },
};
